name: storybook_test

on: [push]

jobs:
  storybook_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: StorybookTest
        uses: ./.github/actions/sbtest
        env:
          SUPABASE_API_URL: ${{ secrets.SUPABASE_API_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
